### ISSUE TITLE
Deliver first version!

### ISSUE THREAD

**Issue by ju5tu5** [SjorsWijsman/eenwoud#7]
Please deploy something on Vercel soon, it might be a first/ crude version of your app. The svelte setup looks nice and i can see you are working on components and sections, but i can't see anything working.

**Comment by SjorsWijsman** [comment]
We tried deploying to Heroku instead because of issues with a .node file not playing nice with the Vercel adapter. That didn't solve the issue so we're migrating back to Vercel. Deployment should be back up today/tomorrow.

**Comment by SjorsWijsman** [comment]
Preview & Production environments are back up. #8
